# <NEDUR/code> PY003 - Indexação

Indexações são formas de acessar elementos dos objetos criados. 

A partir delas, podemos observar, verificar ou transformar informações parciais ou totais de um objeto. 

Em Python, podemos usar símbolos, como [], e algumas funções, como `loc` e `i.loc()`. 

## Indexação de vetores: 

Como exemplo, crie o vetor abaixo no seu notebook: 

In [1]:
import numpy as np
y = np.array(["NEDUR", "UFPR", "Programação", "NEDURcode", "Python"])

Podemos acessar o primeiro elemento usando:

In [2]:
y[0]

'NEDUR'

É isso mesmo! Em Python, os elementos são armazenados começando com o índice zero. Logo, para selecionar o quarto elemento, precisamos chamar o índice três:

In [3]:
y[3]

'NEDURcode'

Ou ainda, podemos começar a seleção pela ordem inversa. O último elemento é o -1, o penúltimo é o -2, e assim por diante. Ou seja, também podemos selecionar o quarto elemento, utilizando a posição -2: 

In [4]:
y[-2]

'NEDURcode'

Para remover algum elemento, podemos utilizar a função `np.delete()`. Por exemplo, para deletar o elemento com índice 2 (terceiro elemento), podemos usar: 

In [5]:
np.delete(y, 2)

array(['NEDUR', 'UFPR', 'NEDURcode', 'Python'], dtype='<U11')

Podemos também utilizar a indexação juntamente com funções.

Crie um vetor numérico: 

In [6]:
v = np.array([1, 2, 3, 4, 5])

Para acessar os elementos iguais a dois: 

In [7]:
v[v==2]

array([2])

Ou, os elementos menores do que 4: 

In [8]:
v[v<4]

array([1, 2, 3])

A mesma lógica se aplica para listas! 

Tente as mesmas operações, criando v como uma lista: 

In [9]:
y_lista = ["NEDUR", "UFPR", "Programação", "NEDURcode", "Python"]

In [10]:
y_lista[-1]

'Python'

No caso de matrizes, as regras são semelhantes às listas e vetores, mas agora precisamos considerar que esses objetos são bidimensionais. 

Vamos começar com a matriz abaixo:

In [11]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(C)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Para selecionar o elemento da primera linha e segunda coluna, podemos usar: 

In [12]:
C[0,1]

2

Ou: 

In [13]:
C[0][1]

2

A segunda linha pode ser selecionada com: 

In [14]:
C[1,:]

array([4, 5, 6])

Ou com: 

In [15]:
C[1]

array([4, 5, 6])

Por sua vez, para selecionar a primeira coluna, podemos usar: 

In [16]:
C[:,0]

array([ 1,  4,  7, 10, 13])

Para selecionar da segunda à quarta linha (índices de 1 à 3), podemos usar:

In [17]:
C[1:4, :]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Observe que o último índice (4), não está incluído na seleção. 

De forma similar, para selecionarmos as duas primeiras colunas, podemos usar: 

In [18]:
C[: , 0:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14]])

## Indexação em Data Frames

Em Data Frames, a indexação é um pouco diferente. Vamos criar uma base de dados fictícia para isso.  

In [19]:
import pandas as pd
df = pd.DataFrame([["João", 20, 1000],
                   ["Maria", 25, 2500],
                   ["Joaquim", 40, 3000]], 
                  columns = ["nome", "idade", "salário"])
df

nome  idade  salário
0     João     20     1000
1    Maria     25     2500
2  Joaquim     40     3000

Para selecionar a coluna com os salários, podemos usar: 

In [20]:
df[["salário"]]

salário
0     1000
1     2500
2     3000

De forma similar, podemos selecionar utilizando operadores lógicos. Por exemplo, podemos selecionar pessoas com salários acima de 2.000: 

In [21]:
df[df["salário"]>2000]

nome  idade  salário
1    Maria     25     2500
2  Joaquim     40     3000

Outra forma de selecionar linhas e colunas específicas é por meio dos métodos `iloc()` e `loc()`.

No método `iloc()`, usamos apenas os índices das linhas e colunas. 

Por exemplo, podemos selecionar apenas a idade de Maria com: 

In [22]:
df.iloc[1,1]

25

Ou, utilizando o nome da coluna, com o método `loc()`: 

In [23]:
df.loc[1,"idade"]

25

Para selecionar todas as informações de Maria, podemos usar: 

In [24]:
df.iloc[1]

nome       Maria
idade         25
salário     2500
Name: 1, dtype: object

## EXTRAS

Quer dar uma olhada em informações gerais da sua base de dados? Utilize o método describe:

In [25]:
df.describe()

idade      salário
count   3.000000     3.000000
mean   28.333333  2166.666667
std    10.408330  1040.833000
min    20.000000  1000.000000
25%    22.500000  1750.000000
50%    25.000000  2500.000000
75%    32.500000  2750.000000
max    40.000000  3000.000000

Para deletar uma linha ou coluna, você pode usar o que aprendeu com a indexação. Por exemplo, se quisermos deletar as informações sobre João, podemos usar: 

In [26]:
df.drop([0, ])

nome  idade  salário
1    Maria     25     2500
2  Joaquim     40     3000